### ISSUE TITLE
Error while starting server with the release jar file

### ISSUE THREAD

**Issue by Considerated** [Swofty-Developments/HypixelSkyblockRecode#13]
```[17:01:00 ERROR]: Error occurred while enabling SkyblockSandboxBase v0.1 (Is it up to date?)
java.lang.IllegalArgumentException: The connection string is invalid. Connection strings must start with either 'mongodb://' or 'mongodb+srv://
        at com.mongodb.ConnectionString.<init>(ConnectionString.java:293) ~[?:?]
        at com.mongodb.client.MongoClients.create(MongoClients.java:61) ~[?:?]
        at net.atlas.SkyblockSandbox.database.mongo.MongoCoins.connect(MongoCoins.java:43) ~[?:?]
        at net.atlas.SkyblockSandbox.SBX.onEnable(SBX.java:130) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[17:01:00 INFO]: [SkyblockSandboxBase] Disabling SkyblockSandboxBase v0.1
[17:01:00 ERROR]: Error occurred while disabling SkyblockSandboxBase v0.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.spawners" is null
        at net.atlas.SkyblockSandbox.SBX.onDisable(SBX.java:192) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:833) [?:?]```

I'm getting this error while launching the server
Minecraft Server Version: Paper 1.8.8

**Comment by Maploop** [comment]
You need to add a MongoDB database URI into your config file, also I do not suggest trying to set this up if you do not have coding experience

**Comment by Considerated** [comment]
may i know where the config file is? i don't seem to find in the repo, nor in the plugins folder where i've downloaded the release in

**Comment by Considerated** [comment]
found it in dbinfo.yml, but the error still persists

**Comment by Considerated** [comment]
![image](https://user-images.githubusercontent.com/78251960/194747550-365d7c33-532c-46ee-9745-5cf19b878232.png)

But, I still get this error:
![image](https://user-images.githubusercontent.com/78251960/194747584-7a6e1357-072b-4842-be69-b37ec89b4865.png)

I believe this is a problem with the connection string being invalid, but I still get the same error.
For info, I'm using the release file found in this repository and I haven't compiled this myself

**Comment by olehrstm** [comment]
You also need to Change the URI in the Code, Like in the Mongo Files. Also you need to Just leave the URI in the config as it was

**Comment by Considerated** [comment]
ok. will update
