### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by frhdrhgdetrhdhg** [Swofty-Developments/HypixelSkyblockRecode#18]
idk what version this is for i tried 1.8.8 it didnt work...

**Comment by frhdrhgdetrhdhg** [comment]
also says this 
Error downloading original jar
java.io.FileNotFoundException: ...
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at java.base/java.net.URL.openStream(URL.java:1161)
        at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1460)
        at com.destroystokyo.paperclip.Paperclip.main(Paperclip.java:90)
